name:                nma
version:             0.1.0.0
github:              "githubuser/nma"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/nma#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - text
  - aeson
  - wreq
  - lens
  - xeno
  - bytestring
  - generic-deriving

executables:
  nma-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nma
    - text
    - optparse-applicative

tests:
  nma-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-orphans -Wno-type-defaults
    dependencies:
    - nma
    - QuickCheck
    - HUnit
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - bytestring
    - checkers
    - text
